### ISSUE TITLE
User test - Boek verwijderen leestlijst

### ISSUE THREAD

**Issue by Nazneen05x** [Annevd/fix-the-flow-interactive-website#9]
**Taak/scenario:**

Mijn complimenten, je hebt je taak en scenario echt goed beschreven (verwoord), ik wist gelijk wat ik moest doen.😁

**Feedback Website (test):**

Het testen ging voor mijn gevoel goed. De verwijder knop is goed (duidelijk) gemaakt en te vinden. Ik was wel in het begin overweldigd toen ik voor het eerst op je website kwam, omdat er veel gebeurde op je website, het is soort van druk en veel witruimte. Je witruimte beter verdelen.

**Hier een voorbeeld (inspiratie) van een oude fdnd student**

https://maikangn.github.io/all-human-accessible-website/

<img width="500" alt="Scherm­afbeelding 2023-12-16 om 18 12 54" src="https://github.com/Annevd/fix-the-flow-interactive-website/assets/112861261/90726be6-3a65-4486-b2a2-0656bf6e9c53">

Verder ben je goed bezig!😄

**Comment by Annevd** [comment]
Ik heb een aantal knoppen dat te maken had met lijsten bekijken en maken weggehaald omdat deze al op de vorige pagina te vinden zijn. Ik hoop dat dat het al iets rustiger heeft gemaakt.

![image](https://github.com/Annevd/fix-the-flow-interactive-website/assets/144004647/0ee265f9-ae2f-4564-a6f6-86c7ba73e5f6)

**Comment by Nazneen05x** [comment]
Veel beter! oogt zeker nu rust! goed bezig!
